### ISSUE TITLE
Using isValidSignature with body as an object

### ISSUE THREAD

**Issue by Snugug** [sanity-io/webhook-toolkit#15]
I'm attempting to use this to verify a signature but I'm getting the request body already parsed as an object, and attempting to run this as-is with a JSON stringified body object isn't working. How can I use this if I don't have direct access to the `request` object?

**Comment by daniel-kratohvil** [comment]
If you already have the body as a JSON object, you can try passing it a a string by using `JSON.stringify(body)`. That's what worked in my case with Next.js 13.4:

```
import { isValidSignature, SIGNATURE_HEADER_NAME } from '@sanity/webhook';
import { NextResponse } from 'next/server';
import { revalidateTag } from 'next/cache';

const secret = process.env.SANITY_STUDIO_REVALIDATE_SECRET ?? '';

export async function POST(request: Request) {
  const req = await request.json();
  const signature = request.headers.get(SIGNATURE_HEADER_NAME) || '';

  if (!isValidSignature(JSON.stringify(req), signature, secret)) {
    return NextResponse.json({ message: 'Invalid signature' }, { status: 401 });
  }

  try {
    // Your revalidation logic here, i.e. revalidateTag('all');

    return NextResponse.json({ message: `Cache revalidated` });
  } catch (err: any) {
    console.log(err);
    return NextResponse.json({ message: 'Error revalidating', error: err.message }, { status: 500 });
  }
}
```

**Comment by Mtillmann** [comment]
@daniel-kratohvil thanks, your approach works great with google cloud functions framework as well:

```es6
import { isValidSignature, SIGNATURE_HEADER_NAME } from '@sanity/webhook';
export async function myEntryPoint(req, res) {
    const isValid = isValidSignature(JSON.stringify(req.body), req.headers[SIGNATURE_HEADER_NAME], process.env.SANITY_WEBHOOK_SECRET);
    if (!isValid) {
        return res.send(401);
    }
//...code
```

**Comment by rexxars** [comment]
**Note:** The approach of re-encoding the body like this may unexpectedly fail. This is because JSON is not guaranteed to be encoded the same way in different encoders/languages. For instance, the character `Ω` can be encoded as simply `"Ω"`, but some JSON encoders _may_ also encode it as `"\u03A9"`. Similarly, the order of keys in an object is not required to be maintained, which _also_ might create different signatures.

**Comment by Mtillmann** [comment]
I'll add this here as my other issue is already closed. Due to the json encode issues mentioned above I believe that it is currently not possible to use the validation with google cloud functions. I've tried and set up an explicit express instance inside my CF in order to use the middleware, as the example in the readme suggests,  but every request fails:

```log
 Error: [@sanity/webhook] `request.body` was not a string/buffer - this can lead to invalid signatures. See the [migration docs](https://github.com/sanity-io/webhook-toolkit#from-parsed-to-unparsed-body) for details on how to fix this.
    at assertValidRequest (/workspace/node_modules/@sanity/webhook/dist/index.js:60:11)
    at ensureSignedRequest (/workspace/node_modules/@sanity/webhook/dist/index.js:111:7)
...
```

[Google's documentation](https://cloud.google.com/functions/docs/concepts/nodejs-runtime#using_middleware_to_handle_http_requests) says:

> This means that HTTP requests should be considered to have been fully read by the time your code is executed. The nesting of ExpressJS apps should be used with this caveat—specifically, middleware that expects the body of a request to be unread might not behave as expected.

It's a bit disappointing but I'll use a static secret header to make sure that requests are send by sanity.

**Comment by stipsan** [comment]
@Mtillmann [you can filter by IP to make up for not being able to verify the body checksum.](https://www.sanity.io/docs/webhooks#2a62c34f67fa)
Closing this as payload verification will continue to require reading the body as-is, for the reasons outlined by @rexxars
