### ISSUE TITLE
isValidRequest with AWS Lambda handler

### ISSUE THREAD

**Issue by ratkorle** [sanity-io/webhook-toolkit#7]
Hi, this might not be an issue. I just can find how to validate the secret in my AWS Lambda handler.

What I have tried is:

const { isValidRequest } = require("@sanity/webhook");

```
exports.handler = async (event, context) => {
  try {
    if (
      !isValidRequest(JSON.parse(event.body), process.env.SANITY_HOOK_SECRET)
    ) {
      console.log("UNAUTHORIZED");
      return ApiResponse.Unauthorized("Unauthorized");
    }
}
```

and also

```
exports.handler = async (event, context) => {
  try {
    if (
      !isValidRequest(event, process.env.SANITY_HOOK_SECRET)
    ) {
      console.log("UNAUTHORIZED");
      return ApiResponse.Unauthorized("Unauthorized");
    }
}
```

I get Unauthorized within these 2 approaches. As I can see in `event.body`  I get value `_rev: 'something'`. 
In event.headers : 'sanity-webhook-signature': 't=1634asdasdasd'

Suggestions?

**Comment by gtwebsite** [comment]
Same, deployed to Netlify, they are also using AWS Lambda

**Comment by ajereos-circadence** [comment]
> Same, deployed to Netlify, they are also using AWS Lambda

Seems to working, just missed few things. when testing add 

```
t=xxx,v1=xxx
```

**Comment by cbovis** [comment]
I guess you're not looking for a solution anymore but for anyone that's looking for the same thing here's the solution I found.

You're unable to use `isValidRequest` because it expects an object for the request body whereas the body in a Lambda event is already stringified. With this in mind we can jump straight to the next layer down, `isValidSignature`. This function expects a stringified body (already provided by Lambda), the signature header and your signature.

This would look something like:

```typescript
import { isValidSignature, SIGNATURE_HEADER_NAME } from "@sanity/webhook";

// ...

const signature = event.headers[SIGNATURE_HEADER_NAME];
const payload = event.body;
const isValid = isValidSignature(payload, signature, process.env.SANITY_HOOK_SECRET);

// ...

```
